#logging.level.org.springframework.web: DEBUG

spring:
  datasource:
   url: jdbc:postgresql://localhost/camunda
   username: postgres
   password: root
   driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true

camunda:
  bpm:
    job-execution:
      core-pool-size: 20
      max-pool-size: 60
      deployment-aware: true
    admin-user:
      id: admin
      password: admin
    filter:
      create: All tasks
    database:
      schema-update: true
    jpa:
      handle-transaction: false
